cluster:
  data:
    record:
      maxKey: 4611686018427387904  # math.MaxInt64
      dataSizeMin: 1024  # 1KB
      dataSizeMax: 10240  # 10KB
    file:
      path: data/test
      blockSize: 536870912  # 512MB
      blockNum: 3
  mapper:
    listen:
      addresses:
        - :8000
        - :8001
        - :8002
  master:
    dial:
      addresses:
        - localhost:8000
        - localhost:8001
        - localhost:8002
    request:
      timeout: 30000  # ms
local:
  data:
    record:
      num: 10000
      topN: 10
